name: test build arg
  
on:  
  workflow_dispatch:  
  
jobs:  
  build:  
    runs-on: [self-hosted, Ubuntu-22.04]      
  
    steps:  
      - name: Checkout code  
        uses: actions/checkout@v2  
  
      - name: Set up Docker Build  
        run: |  
          echo "Creating a sample Dockerfile"  
          mkdir -p dockerfiless/Dockerfile  
          cat <<EOF > dockerfiles/Dockerfile/Dockerfile  
          ARG BASE_IMAGE  
          FROM \${BASE_IMAGE}  
  
          ARG TEST_ARG  
          RUN echo "Test argument: \${TEST_ARG}"  
          RUN echo "Base image: \${BASE_IMAGE}"  
          EOF  
  
      - name: Build Docker image  
        run: |  
          base_image="ubuntu:20.04"  # Change this to test different base images  
          echo "Building Docker image with base image: $base_image"  
          docker build --build-arg BASE_IMAGE="$base_image" --build-arg TEST_ARG="HelloWorld" -t test_image -f dockerfiles/Dockerfile/Dockerfile dockerfiles/Dockerfile  
  
      - name: Run Docker image  
        run: |  
          echo "Running Docker image to check output"  
          docker run --rm test_image
