name: Test Build Arg  
  
on:    
  workflow_dispatch:    
  
jobs:    
  build:    
    runs-on: [self-hosted, Ubuntu-22.04]        
  
    steps:  
      - name: Set env variables  
        run: |  
          echo "Setting environment variables..."  
          echo "XRT_VERSION_PATCH=$(($GITHUB_RUN_NUMBER+717))" >> $GITHUB_ENV  
          echo "PATH=/usr/bin:$PATH" >> $GITHUB_ENV  
  
      - name: Checkout PR  
        uses: actions/checkout@v3  
        with:  
          fetch-depth: 0  
          path: ${{ github.workspace }}/${{ env.XRT_VERSION_PATCH }}  
          submodules: recursive  
  
      - name: Build Docker image  
        run: |  
          package_files="Hello"
          base_image="HelloWorld"  
          echo "Using base image: $base_image"  
          #docker build --build-arg BASE_IMAGE="$base_image" -t hello-world-image ${{ github.workspace }}/${{ env.XRT_VERSION_PATCH }}/Dockerfile  
          docker build --build-arg PACKAGE_FILE="$package_file" --build-arg BASE_IMAGE="$base_image"  -t hello-world-image ${{ github.workspace }}/${{ env.XRT_VERSION_PATCH }}/Dockerfile
  
      - name: Run Docker container  
        run: |  
          docker run hello-world-image 
